loginserver.host = *
loginserver.port = 2107
gameserver.host = 127.0.0.1
gameserver.port = 9015
revision = 0x0102
server.connection.timeout.ms = 10000
accept.new.gameserver = true
server.account.autocreate = true
server.account.autocreate.access.level = 0
server.show.license = true
server.account.inactive.access.level = -127
rsa.padding.mode.gameserver = RSA/ECB/nopadding
rsa.padding.mode.client = RSA/ECB/PKCS1Padding
database.url = postgres://l2unity:l2unity@localhost:5432/l2unity?sslmode=disable
logger.print.received-packets = false
logger.print.sent-packets = false
logger.print.cryptography = false
