GameserverHostname = *
GameserverPort = 7778
LoginHost = 127.0.0.1
LoginPort = 9015
RequestServerID = 1
AcceptAlternateID = true
MaximumOnlineUsers = 100
UseBlowfishCipher = true
ServerGMOnly = false
Developer = false
PacketHandlerDebug = false
database.url = postgres://l2unity:l2unity@localhost:5432/l2unity?sslmode=disable
