#
# Docker overlay for the Java login server.
# Bind on all interfaces so the gameserver container can register.
#

loginserver.host = *
loginserver.port = 2107
revision = 0x0102
gameserver.host = *
gameserver.port = 9015
server.connection.timeout.ms=10000

database.jdbc.url=jdbc:mariadb://mariadb:3306/l2unity
database.jdbc.username=l2unity
database.jdbc.password=l2unity

accept.new.gameserver = True
rsa.padding.mode.gameserver=RSA/ECB/nopadding
rsa.padding.mode.client=RSA/ECB/PKCS1Padding
server.account.autocreate = true
server.account.autocreate.access.level = 0
server.show.license = true
server.account.inactive.access.level = -127

logger.print.received-packets=true
logger.print.sent-packets=true
logger.print.cryptography=false
